ALTER TABLE expenses DROP CONSTRAINT IF EXISTS amount_positive;
ALTER TABLE expenses ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE users DROP COLUMN IF EXISTS password_hash;
ALTER TABLE users DROP COLUMN IF EXISTS email;